# Generated by Django 5.0.1 on 2024-02-09 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_remove_art_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='image',
            field=models.ImageField(default='art1.jpg', upload_to=''),
        ),
        migrations.AddField(
            model_name='artist',
            name='image',
            field=models.ImageField(default='art2.jpg', upload_to=''),
        ),
    ]
