# Generated by Django 5.0.1 on 2024-02-09 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_art_image_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='image',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='artist',
            name='image',
            field=models.CharField(max_length=250),
        ),
    ]
