# Generated by Django 5.0.1 on 2024-02-09 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_art_image_alter_artist_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='artist',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
