# Generated by Django 5.0.1 on 2024-02-09 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_art_description_alter_artist_about'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='fact',
        ),
    ]
