# Generated by Django 5.0.1 on 2024-02-09 04:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_art_fact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='style',
        ),
    ]
